export const CONFIG = {
  PORT: parseInt(process.env.PORT || '3001'),
  CLIENT_URL: process.env.CLIENT_URL || 'http://localhost:5173',

  HAND_SIZE_PERKS: 7,
  HAND_SIZE_REDFLAGS: 3,
  WIN_SCORE: 7,
  MAX_PLAYERS: 10,
  MIN_PLAYERS: 3,

  PERK_TIMER: 0,
  RED_FLAG_TIMER: 0,
  REVEAL_TIMER: 5,
  ARGUMENT_TIMER: 0,
  JUDGING_TIMER: 0,
  ROUND_RESULT_TIMER: 3,

  RECONNECT_GRACE_MS: 120_000,
  STALE_ROOM_MS: 1_800_000,
  CLEANUP_INTERVAL_MS: 300_000,
} as const;
